---
title: "Eksamen"
output:
  html_document: default
  pdf_document: default
date: '2022-06-06'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Kandidatnummer: 62
#Gruppenummer: 8
#Githublink: https://github.com/JonasMorberg/SOK-1005-Eksamen

#Installerer pakker
library(dplyr)
library(tidyverse)
library(lubridate)

#De 6 datasettene
AppWichStoreAttributes
county_crime
county_demographic
county_employment
WEEKLY_SALES_10STORES
WEEKLY_WEATHER

#Starter med å fikse i litt i de 6 datasettene før jeg slår de sammen
#Her bytter jeg navn på Store_county og Store_Weather_Station
#Dette er mulig fordi inneholdet i disse radene er lik som i de andre datasettene
AppWichStoreAttributes2 <- AppWichStoreAttributes %>% rename(County_Name = Store_County, Weather_Station = Store_Weather_Station)
head(AppWichStoreAttributes2)

#formaterer datoene til Weather_Date raden
WEEKLY_WEATHER$Weather_Date <- 
  as.Date(WEEKLY_WEATHER$Weather_Date, format = "%d/%m/%Y") 
WEEKLY_WEATHER

#Endrer visningen til datoene i hoveddatasettet
WEEKLY_SALES_10STORES_1 <- WEEKLY_SALES_10STORES %>% mutate(Date = as.Date(with(WEEKLY_SALES_10STORES, paste(Year, Month, Day,sep="-")), "%Y-%m-%d"))

#bytter Store_num i WEEKLY_SALES_10STORES, slik at det blir likt som andre dataset
WEEKLY_SALES_10STORES2 <- WEEKLY_SALES_10STORES_1 %>% 
  rename(Store_Num = Store_num)




#OPPGAVE 1

#Den første oppgaven er å skrive R kode som slår sammen de 6 datasettene til et stort datasett.

#Du må benytte de variablene som de ulike datasettene #har til felles for å gjøre dette. Denne prosessen skal kort dokumenteres og kommenteres.
#Så skal jeg benytte forskjellige variabler for å kombinere de til et dataset
#Her bruker jeg left_join for å koble sammen de 6 datasettene, og så starter jeg med det største

First <- left_join(WEEKLY_SALES_10STORES2, AppWichStoreAttributes2, by = "Store_Num")
First

Second <- left_join(First, county_crime, by = c("County_Name" = "ï..County_Name"))
Second

Third <- left_join(Second, county_demographic, by = "County_Name")
Third

Fourth <- left_join(Third, county_employment, by = c("County_Name" = "ï..County_Name"))
Fourth

Last <- left_join(Fourth, WEEKLY_WEATHER, by = c("Date" = "Weather_Date"))
Last


#Så sletter jeg år, måned og dag, siden Dato raden allerede viser det
Last1 <- subset(Last, select = -c(Year, Month, Day))
head(Last1)


#Oppgave 2

#Dataene skal benyttes til en ukentlig salgsrapport til et enkelt utsalg.
#Dette skal være en kortsiktig rapport
#Jeg har valgt uke 25 og utsalg nummer 23
#I denne oppgaven skal jeg vise:
#Det de selger mest og minst av i denne perioden
#Forskjellen mellom uker i totale salg
#Sammenhengen mellom pris og profitt


#Starter med å lage et datasett med bare uke 25 og utsalg nummer 23
Uke <- Last1 %>% filter(Weather_Week==25)
Uke


Utsalg <- Last1 %>% filter(Store_Num==23)
Utsalg

#Så setter jeg sammen disse, mens jeg velger hvilke kollonner som skal være med
#Dette er fordi det er mye informasjon som ikke er like relevant

Salg_25_23 <- Last1 %>% filter(Weather_Week==25, Store_Num==23) %>%
select(Description, Price, Sold, Sales, Tot_Sls,Unit_Cost,Cost, Cost_Percent,
Margin, Profit,   Date,Store_Name,Store_City,  County_Name ,Store_State ,
Weather_Station.x)
head(Salg_25_23)

#Første jeg skal vise er hva de selger mest og minst av
#Første tabellen viser alle varene sine salg
aggregate(x= Salg_25_23$Sales,
          by= list(Salg_25_23$Description),
          FUN=max)
          
        
#Her vises det varen med mest og minst salg
max(Salg_25_23$Sales)

min(Salg_25_23$Sales)


#Her kan man se at varen med mest salg er "REGULAR SAVORY TURKEY" og minst var "REGULAR SUB OR SALAD, REWARD"

#Her skal jeg velge en annen uke for så å se forskjellen mellom totale salg på
#forskjellige uker, her er det uke 25 og uke 15
Salg_15_23 <- Last1 %>% filter(Weather_Week==15, Store_Num==23) %>%
select(Description, Price, Sold, Sales, Tot_Sls,Unit_Cost,Cost, Cost_Percent,
Margin, Profit,   Date,Store_Name,Store_City,  County_Name ,Store_State ,
Weather_Station.x)
head(Salg_15_23)

#Her er den totale summen for salgene i uke 15 og 25,
#så finner forskjellen mellom disse
sum(Salg_15_23$Sales)

sum(Salg_25_23$Sales)

Salg_diff = ((sum(Salg_25_23$Sales)/sum(Salg_15_23$Sales)-1))*100
Salg_diff


#Her skal jeg lage et scatterplot med å vise hvilke varer 
#som har minst og høyest profitt og om prisen på varene har noe å si

profitt <- Salg_25_23[order(-Salg_25_23$Profit),]
head(profitt)

Profitt1 <- profitt %>% select(Description, Price, Sold, Sales, Tot_Sls,
Unit_Cost,  Cost, Cost_Percent, Margin, Profit, Date)

#Her kan man se i dette enkle plottet at pris og profitt ikke har noen stor 
#sammenheng, dette er nok fordi bedriften er i fullkommen konkurranse.
#Da er det vanskeligere å kunne sette opp prisen, fordi da taper man salg hvis
#konkurransen ikke også gjør dette. Så vil si det er lurest å følge konkurransen
#sin prissetting.
plot(Profitt1$Price, Profitt1$Profit, xlab= "Pris i dollar", ylab="Profitt",
main= "Scatterplot for pris og profitt", pch=16)



#Oppgave 3

#Månedlig salgsrapport på aggregert nivå til konsernledelsen
#Dette skal være mer en Langsiktig rapport
#Velger Juni som hovedmåned for salgsrapporten

Salg_mnd <- Last %>% filter(Month==6) %>% select(Description, Price, Sold,
Sales, Tot_Sls,Unit_Cost,Cost, Cost_Percent, Margin, Profit,Date,Store_Name,
Store_City,  County_Name ,Store_State, Weather_Station.x, Weather_Week) 
head(Salg_mnd)

#Starter med å vise forskjellen på salg og profitt
#fra første og siste uken i Juni
Salg_mnd_20 <- Last1 %>% filter(Weather_Week==20) %>% select(Description, Price,
Sold,Sales, Tot_Sls,Unit_Cost,Cost, Cost_Percent, Margin, Profit,Date,
Store_Name,Store_City,  County_Name ,Store_State,
Weather_Station.x, Weather_Week) 

Salg_mnd_24 <- Last1 %>% filter(Weather_Week==24) %>% select(Description,
Price, Sold,Sales, Tot_Sls,Unit_Cost,Cost, Cost_Percent,
Margin, Profit,Date,Store_Name,
Store_City,  County_Name ,Store_State, Weather_Station.x, Weather_Week) 

sum(Salg_mnd_20$Sales)

sum(Salg_mnd_24$Sales)


sum(Salg_mnd_20$Profit)

sum(Salg_mnd_24$Profit)

#Her er forskjellen mellom starten og slutten på salgene i Juni
Salg_mnd_sales_diff = (sum(Salg_mnd_24$Sales)/sum(Salg_mnd_20$Sales)-1)*100
Salg_mnd_sales_diff

#Og her er forskjellen på profitten mellom starten og slutten i Juni
Salg_mnd_profit_diff = (sum(Salg_mnd_24$Profit)/sum(Salg_mnd_20$Profit)-1)*100
Salg_mnd_profit_diff


#Sjekke hvilke måned de selger mest varer, dette er for å se
#hvor de burde øke produksjonen

Salg_year <- Last %>% select(Month, Sales)
head(Salg_year)

ggplot(Salg_year, aes(x=Month)) + geom_bar(fill="blue", width=0.5) + 
labs("Sammenligning av salg for 12 måneder") + ylab("Sales")+xlab("Months") + 
scale_x_continuous(breaks = 1:12)

#Her kan man se i forrige plot at det er mest salg i april, så mulighet å selge mer spesielt da.

#Nå skal jeg lage et paiplot om hvilke county det er som har mest profitt
#Dette er for å vise hvilke de burde fokusere mest på og hvilke de burde minst
#Her velger jeg også Juni som måned
#Starter med å lage et datasett for plottet
county_prof <- Last %>% group_by(Month, County_Name) %>% 
summarise(Maks_profit = sum(Profit)) %>%
mutate(prosent = 100 * Maks_profit /sum(Maks_profit)) %>% filter(Month==6)
head(county_prof)

#lager dette slik at jeg kan få navn på paiplottet
county_names <- c("Appleton County", "Farm County", "Lake County", "Power County", "Rail County", "River County")

#Dette er et paiplot som viser de forskjellige andelene av profitten til de forskjellige fylkene
pie(county_prof$Maks_profit, labels = county_names, main = "Profitt andelen av fylkene")


#Oppgave 4

#I denne opppgaven skal det handle om mulighetene konsernledelsen kan gjøre for et nytt utsalg
#Her er paiplottet noe som man kan bruke, den forteller oss at Power county og Farm county er de fylkene med mest profitt
#Det viser også at Rail county er klart det fylket med minst profitt i forhold til de andre
#Noe annet som kan hjelpe er i den ukentlige rapporten, så fikk man vite at "REGULAR SAVORY TURKEY" ble solgt mest og minst var "REGULAR SUB OR SALAD, REWARD"
#Hadde også et plot der man kunne se hvilke måneder det er mest salg, slik at man vet hvilke man burde produsere mer. De høyest månedene var April, Juli, September og Desember. Det minste var Februar og August.
#Så dette er noen tips til konsernledelsen om hva de burde tenke på og hvor de burde ha dette nye utsalget.

#Noe jeg ikke har gått inn på er fylkene sine forbrytelser
County_forbrytelser <- county_crime %>% select(ï..County_Name, County_Total_Crimes)
County_forbrytelser

#Her kan man se at Appleton og Power fylke har mest forbrytelser, mens Farm og River har minst. Så ser ut som på mange av tallene viser til at Farm fylket ser best ut på dette, men også en av de fylkene med mest profitt. Så vil tipse dem med å starte det nye utsalget i Farm county.











